baseurl = "/"
title = "modelplotr"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Jurriaan Nagelkerke"
disqusShortname = "XXX"
googleAnalytics = "XXX"

# ignore certain files as recommended
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Jurriaan Nagelkerke"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Introduction to modelplotr"
    description = ""
    github = "https://github.com/jurrr/modelplotr"
    linkedin = "https://www.linkedin.com/in/jnagelkerke/"
    email = "jurriaan.nagelkerke@gmail.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
